name: Build N Test # Not Dockerized

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  
  build-n-test:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3
      - name: build
        run: echo "hey"
